### ISSUE TITLE
PHP 7.2 requirement

### ISSUE THREAD

**Issue by blubberblah** [frankkoornstra/elastic-apm-agent#24]
Hi Frank,
I've noticed the explicit PHP 7.2 requirement in composer.json. Are there any plans to release a PHP 7.1 version of the agent?
Regards,
Holger

**Comment by frankkoornstra** [comment]
Hil Holdger,

Sorry for the late reply! Dismissing one notification and I'm neglecting your message :( Sorry to disappoint but PHP 7.2 will stay the minimum requirement since [active support for 7.1 has ended in December 2018](https://secure.php.net/supported-versions.php). Also a lot of the features in 7.2 are quite nice so sorry to disappoint but hope you understand.
